"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STRING_KEYWORDS = void 0;
/** String functions, conversion functions and the LONGSTRING family. */
exports.STRING_KEYWORDS = [
    {
        name: "LEN",
        kind: "function",
        category: "Strings",
        syntax: ["LEN( string$ )"],
        summary: "Number of characters in a string.",
        example: ['PRINT LEN("Hello")   \' 5'].join("\n"),
        snippet: "LEN(${1:string$})",
    },
    {
        name: "LEFT$",
        kind: "function",
        category: "Strings",
        syntax: ["LEFT$( string$, nbr )"],
        summary: "The leftmost nbr characters of a string.",
        example: ['PRINT LEFT$("Hello", 3)   \' Hel'].join("\n"),
        snippet: "LEFT$(${1:string$}, ${2:count})",
    },
    {
        name: "RIGHT$",
        kind: "function",
        category: "Strings",
        syntax: ["RIGHT$( string$, nbr )"],
        summary: "The rightmost nbr characters of a string.",
        example: ['PRINT RIGHT$("Hello", 3)   \' llo'].join("\n"),
        snippet: "RIGHT$(${1:string$}, ${2:count})",
    },
    {
        name: "MID$",
        kind: "function",
        category: "Strings",
        syntax: ["MID$( string$, start )", "MID$( string$, start, nbr )"],
        summary: "Substring starting at 'start' (1 based). Without nbr it runs to the end of the string.",
        notes: ["MID$ can also be used on the left of an assignment to overwrite characters in place."],
        example: [
            'PRINT MID$("Hello", 2, 3)   \' ell',
            's$ = "Hello"',
            's$ = MID$(s$, 2)            \' ello',
        ].join("\n"),
        snippet: "MID$(${1:string$}, ${2:start}, ${3:count})",
    },
    {
        name: "INSTR",
        kind: "function",
        category: "Strings",
        syntax: ["INSTR( [start,] string-searched$, string-pattern$ [, size] )"],
        summary: "Position of one string inside another, or zero if it is not found. Search starts at 'start' if given.",
        example: [
            'PRINT INSTR("hello world", "world")      \' 7',
            'PRINT INSTR(8, "aXbXc", "X")             \' 0',
        ].join("\n"),
        snippet: "INSTR(${1:string$}, ${2:search$})",
    },
    {
        name: "UCASE$",
        kind: "function",
        category: "Strings",
        syntax: ["UCASE$( string$ )"],
        summary: "Converts a string to upper case.",
        example: ['PRINT UCASE$("hello")   \' HELLO'].join("\n"),
        snippet: "UCASE$(${1:string$})",
    },
    {
        name: "LCASE$",
        kind: "function",
        category: "Strings",
        syntax: ["LCASE$( string$ )"],
        summary: "Converts a string to lower case.",
        example: ['PRINT LCASE$("HELLO")   \' hello'].join("\n"),
        snippet: "LCASE$(${1:string$})",
    },
    {
        name: "TRIM$",
        kind: "function",
        category: "Strings",
        syntax: ["TRIM$( source$ [, mask$] [, where] )"],
        summary: "Removes leading and trailing characters, spaces by default. 'where' selects leading, trailing or both.",
        example: ['PRINT "["; TRIM$("  padded  "); "]"   \' [padded]'].join("\n"),
        snippet: "TRIM$(${1:string$})",
    },
    {
        name: "SPACE$",
        kind: "function",
        category: "Strings",
        syntax: ["SPACE$( number )"],
        summary: "A string of the given number of spaces.",
        snippet: "SPACE$(${1:count})",
    },
    {
        name: "STRING$",
        kind: "function",
        category: "Strings",
        syntax: ["STRING$( nbr, ascii )", "STRING$( nbr, string$ )"],
        summary: "A string made of one character repeated nbr times.",
        example: ['PRINT STRING$(20, "-")'].join("\n"),
        snippet: 'STRING$(${1:count}, "${2:-}")',
    },
    {
        name: "FIELD$",
        kind: "function",
        category: "Strings",
        syntax: ["FIELD$( string1$, nbr, string2$ [, string3$] )"],
        summary: "Returns field number nbr from a delimited string. string2$ holds the delimiters, string3$ any quote characters.",
        example: [
            'csv$ = "one,two,three"',
            'PRINT FIELD$(csv$, 2, ",")   \' two',
        ].join("\n"),
        snippet: 'FIELD$(${1:string$}, ${2:1}, "${3:,}")',
    },
    {
        name: "CHR$",
        kind: "function",
        category: "Strings",
        syntax: ["CHR$( number )"],
        summary: "The single character with the given character code.",
        example: ["PRINT CHR$(65)   ' A"].join("\n"),
        snippet: "CHR$(${1:code})",
    },
    {
        name: "ASC",
        kind: "function",
        category: "Strings",
        syntax: ["ASC( string$ )"],
        summary: "The character code of the first character of a string.",
        example: ['PRINT ASC("A")   \' 65'].join("\n"),
        snippet: "ASC(${1:string$})",
    },
    {
        name: "STR$",
        kind: "function",
        category: "Conversion",
        syntax: [
            "STR$( number )",
            "STR$( number, m )",
            "STR$( number, m, n )",
            "STR$( number, m, n, c$ )",
        ],
        summary: "Converts a number to a string. m sets the integer digits, n the decimal places, c$ the pad character.",
        example: [
            "PRINT STR$(3.14159, 1, 2)   ' 3.14",
            'PRINT STR$(42, 5, 0, "0")   \' 00042',
        ].join("\n"),
        snippet: "STR$(${1:number})",
    },
    {
        name: "VAL",
        kind: "function",
        category: "Conversion",
        syntax: ["VAL( string$ )"],
        summary: "Converts the leading number in a string to a value. Understands &H, &O and &B prefixes.",
        example: ['PRINT VAL("42.5")', 'PRINT VAL("&HFF")   \' 255'].join("\n"),
        snippet: "VAL(${1:string$})",
    },
    {
        name: "FORMAT$",
        kind: "function",
        category: "Conversion",
        syntax: ["FORMAT$( nbr [, fmt$] )"],
        summary: "Formats a number using a C style format string such as %8.3f or %04d.",
        example: ['PRINT FORMAT$(3.14159, "%8.3f")'].join("\n"),
        snippet: 'FORMAT$(${1:number}, "%${2:8.3f}")',
    },
    {
        name: "HEX$",
        kind: "function",
        category: "Conversion",
        syntax: ["HEX$( number [, chars] )"],
        summary: "Hexadecimal string for a number, zero padded to 'chars' digits if given.",
        example: ["PRINT HEX$(255, 4)   ' 00FF"].join("\n"),
        snippet: "HEX$(${1:number})",
    },
    {
        name: "OCT$",
        kind: "function",
        category: "Conversion",
        syntax: ["OCT$( number [, chars] )"],
        summary: "Octal string for a number, optionally zero padded.",
        snippet: "OCT$(${1:number})",
    },
    {
        name: "BIN$",
        kind: "function",
        category: "Conversion",
        syntax: ["BIN$( number [, chars] )"],
        summary: "Binary string for a number, optionally zero padded.",
        example: ["PRINT BIN$(5, 8)   ' 00000101"].join("\n"),
        snippet: "BIN$(${1:number})",
    },
    {
        name: "BIN2STR$",
        kind: "function",
        category: "Conversion",
        syntax: ["BIN2STR$( type, value [, BIG] )"],
        summary: "Packs a number into its raw bytes as a string. Type is INT8/16/32/64, UINT8/16/32/64, SINGLE or DOUBLE.",
        notes: ["Little endian by default. Add BIG for big endian."],
        example: ["packed$ = BIN2STR$(INT16, 1234)"].join("\n"),
        snippet: "BIN2STR$(${1|INT8,UINT8,INT16,UINT16,INT32,UINT32,INT64,UINT64,SINGLE,DOUBLE|}, ${2:value})",
    },
    {
        name: "STR2BIN",
        kind: "function",
        category: "Conversion",
        syntax: ["STR2BIN( type, string$ [, BIG] )"],
        summary: "Unpacks raw bytes held in a string back into a number.",
        example: ["v = STR2BIN(INT16, packed$)"].join("\n"),
        snippet: "STR2BIN(${1|INT8,UINT8,INT16,UINT16,INT32,UINT32,INT64,UINT64,SINGLE,DOUBLE|}, ${2:string$})",
    },
    {
        name: "JSON$",
        kind: "function",
        category: "Conversion",
        syntax: ["JSON$( array%(), string$ )"],
        summary: "Extracts a value from a JSON document held in a long string array, using a dotted path.",
        example: ['t$ = JSON$(buff%(), "main.temp")'].join("\n"),
        snippet: 'JSON$(${1:buff%}(), "${2:path}")',
    },
    {
        name: "EVAL",
        kind: "function",
        category: "Conversion",
        syntax: ["EVAL( string$ )"],
        summary: "Evaluates an MMBasic expression held in a string.",
        example: ['PRINT EVAL("2 + 3 * 4")   \' 14'].join("\n"),
        snippet: "EVAL(${1:string$})",
    },
    {
        name: "CAT",
        kind: "command",
        category: "Strings",
        syntax: ["CAT s$, n$"],
        summary: "Appends n$ to s$ in place. Much faster than s$ = s$ + n$ for repeated appends.",
        snippet: "CAT ${1:dest$}, ${2:src$}",
    },
    // ------------------------------------------------------------- long strings
    {
        name: "LONGSTRING",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING subcommand ..."],
        summary: "Commands for strings longer than 255 characters, held in integer arrays.",
        notes: [
            "A long string lives in an INTEGER array, so DIM buff%(255) holds up to 2040 bytes.",
            "Subcommands: APPEND, CLEAR, CONCAT, COPY, LCASE, LEFT, LOAD, MID, PRINT, REPLACE, RESIZE, RIGHT, SETBYTE, TRIM, UCASE, BASE64, AES128.",
        ],
        example: [
            "DIM buff%(255)",
            "LONGSTRING CLEAR buff%()",
            'LONGSTRING APPEND buff%(), "hello "',
            'LONGSTRING APPEND buff%(), "world"',
            "LONGSTRING PRINT buff%()",
        ].join("\n"),
        snippet: "LONGSTRING ${1|APPEND,CLEAR,CONCAT,COPY,LEFT,LOAD,MID,PRINT,REPLACE,RESIZE,RIGHT,SETBYTE,TRIM,UCASE,LCASE|}",
    },
    {
        name: "LONGSTRING APPEND",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING APPEND array%(), string$"],
        summary: "Appends a normal string to the end of a long string.",
        snippet: "LONGSTRING APPEND ${1:buff%}(), ${2:string$}",
    },
    {
        name: "LONGSTRING CLEAR",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING CLEAR array%()"],
        summary: "Empties a long string.",
        snippet: "LONGSTRING CLEAR ${1:buff%}()",
    },
    {
        name: "LONGSTRING LOAD",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING LOAD array%(), nbr, string$"],
        summary: "Replaces the long string with nbr characters from string$.",
        snippet: "LONGSTRING LOAD ${1:buff%}(), ${2:nbr}, ${3:string$}",
    },
    {
        name: "LONGSTRING COPY",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING COPY dest%(), src%()"],
        summary: "Copies one long string over another.",
        snippet: "LONGSTRING COPY ${1:dest%}(), ${2:src%}()",
    },
    {
        name: "LONGSTRING CONCAT",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING CONCAT dest%(), src%()"],
        summary: "Appends one long string to another.",
        snippet: "LONGSTRING CONCAT ${1:dest%}(), ${2:src%}()",
    },
    {
        name: "LONGSTRING LEFT",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING LEFT dest%(), src%(), nbr"],
        summary: "Copies the leftmost nbr characters of a long string.",
        snippet: "LONGSTRING LEFT ${1:dest%}(), ${2:src%}(), ${3:nbr}",
    },
    {
        name: "LONGSTRING RIGHT",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING RIGHT dest%(), src%(), nbr"],
        summary: "Copies the rightmost nbr characters of a long string.",
        snippet: "LONGSTRING RIGHT ${1:dest%}(), ${2:src%}(), ${3:nbr}",
    },
    {
        name: "LONGSTRING MID",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING MID dest%(), src%(), start, nbr"],
        summary: "Copies a section out of a long string.",
        snippet: "LONGSTRING MID ${1:dest%}(), ${2:src%}(), ${3:start}, ${4:nbr}",
    },
    {
        name: "LONGSTRING REPLACE",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING REPLACE array%(), string$, start"],
        summary: "Overwrites part of a long string starting at a position.",
        snippet: "LONGSTRING REPLACE ${1:buff%}(), ${2:string$}, ${3:start}",
    },
    {
        name: "LONGSTRING RESIZE",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING RESIZE addr%(), nbr"],
        summary: "Sets the recorded length of a long string.",
        snippet: "LONGSTRING RESIZE ${1:buff%}(), ${2:nbr}",
    },
    {
        name: "LONGSTRING SETBYTE",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING SETBYTE addr%(), nbr, data"],
        summary: "Sets one byte of a long string by index.",
        snippet: "LONGSTRING SETBYTE ${1:buff%}(), ${2:nbr}, ${3:data}",
    },
    {
        name: "LONGSTRING TRIM",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING TRIM array%(), nbr"],
        summary: "Removes nbr characters from the front of a long string.",
        snippet: "LONGSTRING TRIM ${1:buff%}(), ${2:nbr}",
    },
    {
        name: "LONGSTRING UCASE",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING UCASE array%()"],
        summary: "Converts a long string to upper case in place.",
        snippet: "LONGSTRING UCASE ${1:buff%}()",
    },
    {
        name: "LONGSTRING LCASE",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING LCASE array%()"],
        summary: "Converts a long string to lower case in place.",
        snippet: "LONGSTRING LCASE ${1:buff%}()",
    },
    {
        name: "LONGSTRING PRINT",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING PRINT [#n,] src%() [;]"],
        summary: "Prints a long string to the console or an open file number.",
        snippet: "LONGSTRING PRINT ${1:buff%}()",
    },
    {
        name: "LONGSTRING BASE64",
        kind: "command",
        category: "Long strings",
        syntax: ["LONGSTRING BASE64 ENCODE|DECODE in%(), out%()"],
        summary: "Base64 encodes or decodes between two long strings.",
        snippet: "LONGSTRING BASE64 ${1|ENCODE,DECODE|} ${2:in%}(), ${3:out%}()",
    },
    {
        name: "LONGSTRING AES128",
        kind: "command",
        category: "Long strings",
        syntax: [
            "LONGSTRING AES128 ENCRYPT|DECRYPT CBC|ECB|CTR key, in%(), out%() [, iv]",
        ],
        summary: "AES128 encrypts or decrypts a long string.",
        snippet: "LONGSTRING AES128 ${1|ENCRYPT,DECRYPT|} ${2|CBC,ECB,CTR|} ${3:key$}, ${4:in%}(), ${5:out%}()",
    },
    {
        name: "LLEN",
        kind: "function",
        category: "Long strings",
        syntax: ["LLEN( array%() )"],
        summary: "Current length of a long string in characters.",
        snippet: "LLEN(${1:buff%}())",
    },
    {
        name: "LGETSTR$",
        kind: "function",
        category: "Long strings",
        syntax: ["LGETSTR$( array%(), start, length )"],
        summary: "Extracts part of a long string as a normal string.",
        snippet: "LGETSTR$(${1:buff%}(), ${2:start}, ${3:length})",
    },
    {
        name: "LGETBYTE",
        kind: "function",
        category: "Long strings",
        syntax: ["LGETBYTE( array%(), n )"],
        summary: "The byte value at position n of a long string.",
        snippet: "LGETBYTE(${1:buff%}(), ${2:n})",
    },
    {
        name: "LINSTR",
        kind: "function",
        category: "Long strings",
        syntax: ["LINSTR( array%(), search$ [, start] [, size] )"],
        summary: "Position of a substring inside a long string, or zero.",
        snippet: "LINSTR(${1:buff%}(), ${2:search$})",
    },
    {
        name: "LCOMPARE",
        kind: "function",
        category: "Long strings",
        syntax: ["LCOMPARE( array1%(), array2%() )"],
        summary: "Compares two long strings, returning -1, 0 or 1 like a C style compare.",
        snippet: "LCOMPARE(${1:a%}(), ${2:b%}())",
    },
    {
        name: "LINPUT",
        kind: "function",
        category: "Long strings",
        syntax: ["LINPUT( array%(), fnbr, nbr )"],
        summary: "Reads up to nbr bytes from an open file into a long string.",
        snippet: "LINPUT(${1:buff%}(), ${2:fnbr}, ${3:nbr})",
    },
    {
        name: "LMID",
        kind: "command",
        category: "Long strings",
        syntax: ["LMID( array%(), start [, num] ) = string$"],
        summary: "Overwrites characters inside a long string in place.",
        snippet: "LMID(${1:buff%}(), ${2:start}) = ${3:string$}",
    },
];
//# sourceMappingURL=strings.js.map