import { MMBasicKeywordList } from "../keywordTypes";

/** Drawing primitives, colour, framebuffers, sprites, images and touch. */
export const GRAPHICS_KEYWORDS: MMBasicKeywordList = [
  {
    name: "PIXEL",
    kind: "command",
    category: "Graphics",
    syntax: ["PIXEL x, y [, c]", "PIXEL( x, y )"],
    summary:
      "Sets a single pixel. The function form reads the colour of a pixel back.",
    example: ["PIXEL 100, 50, RGB(RED)", "c = PIXEL(100, 50)"].join("\n"),
    snippet: "PIXEL ${1:x}, ${2:y}, ${3:RGB(WHITE)}",
  },
  {
    name: "LINE",
    kind: "command",
    category: "Graphics",
    syntax: [
      "LINE x1, y1, x2, y2 [, [-]LW [, C]]",
      "LINE AA x1, y1, x2, y2 [, LW [, C]]",
      "LINE GRAPH x(), y(), colour",
      "LINE PLOT ydata() [, nbr] [, xstart] [, xinc] [, ystart] [, yinc] [, colour]",
    ],
    summary:
      "Draws a line. LINE AA is antialiased. LINE GRAPH and LINE PLOT draw a whole array as a trace.",
    example: ["LINE 0, 0, 100, 100, 2, RGB(GREEN)"].join("\n"),
    snippet: "LINE ${1:x1}, ${2:y1}, ${3:x2}, ${4:y2}, ${5:1}, ${6:RGB(WHITE)}",
  },
  {
    name: "BOX",
    kind: "command",
    category: "Graphics",
    syntax: ["BOX x, y, w, h [, lw] [, c] [, fill]"],
    summary:
      "Draws a rectangle. lw is the border width, and a fill colour makes it solid.",
    example: ["BOX 10, 10, 80, 60, 2, RGB(BLUE), RGB(BLACK)"].join("\n"),
    snippet: "BOX ${1:x}, ${2:y}, ${3:w}, ${4:h}, ${5:1}, ${6:RGB(WHITE)}",
  },
  {
    name: "RBOX",
    kind: "command",
    category: "Graphics",
    syntax: ["RBOX x, y, w, h [, r] [, c] [, fill]"],
    summary: "Draws a rectangle with rounded corners of radius r.",
    snippet: "RBOX ${1:x}, ${2:y}, ${3:w}, ${4:h}, ${5:5}, ${6:RGB(WHITE)}",
  },
  {
    name: "CIRCLE",
    kind: "command",
    category: "Graphics",
    syntax: ["CIRCLE x, y, r [, lw] [, a] [, c] [, fill]"],
    summary:
      "Draws a circle or ellipse. 'a' is the aspect ratio, 1 for a true circle.",
    example: ["CIRCLE 160, 120, 50, 2, 1, RGB(YELLOW)"].join("\n"),
    snippet: "CIRCLE ${1:x}, ${2:y}, ${3:r}, ${4:1}, ${5:1}, ${6:RGB(WHITE)}",
  },
  {
    name: "ARC",
    kind: "command",
    category: "Graphics",
    syntax: ["ARC x, y, r1, [r2], a1, a2 [, c]"],
    summary:
      "Draws an arc between two angles in degrees, measured clockwise from 12 o'clock.",
    snippet: "ARC ${1:x}, ${2:y}, ${3:r1}, ${4:r2}, ${5:a1}, ${6:a2}, ${7:RGB(WHITE)}",
  },
  {
    name: "TRIANGLE",
    kind: "command",
    category: "Graphics",
    syntax: [
      "TRIANGLE x1, y1, x2, y2, x3, y3 [, c [, fill]]",
      "TRIANGLE SAVE [#]n, x1, y1, x2, y2, x3, y3",
      "TRIANGLE RESTORE [#]n",
    ],
    summary: "Draws a triangle, optionally filled.",
    snippet:
      "TRIANGLE ${1:x1}, ${2:y1}, ${3:x2}, ${4:y2}, ${5:x3}, ${6:y3}, ${7:RGB(WHITE)}",
  },
  {
    name: "POLYGON",
    kind: "command",
    category: "Graphics",
    syntax: [
      "POLYGON n, xarray%(), yarray%() [, bordercolour] [, fillcolour]",
      "POLYGON n(), xarray%(), yarray%() [, bordercolour()] [, fillcolour()]",
    ],
    summary:
      "Draws one or many polygons from coordinate arrays. The array form draws a batch in one call.",
    snippet: "POLYGON ${1:n}, ${2:x%}(), ${3:y%}(), ${4:RGB(WHITE)}",
  },
  {
    name: "BEZIER",
    kind: "command",
    category: "Graphics",
    syntax: ["BEZIER x%(), y%() [, n] [, colour]"],
    summary: "Draws a Bezier curve through the control points in two arrays.",
    snippet: "BEZIER ${1:x%}(), ${2:y%}()",
  },
  {
    name: "FILL",
    kind: "command",
    category: "Graphics",
    syntax: ["FILL x, y, fillcolour [, bordercolour]"],
    summary: "Flood fills an enclosed area starting from a point.",
    snippet: "FILL ${1:x}, ${2:y}, ${3:RGB(WHITE)}",
  },
  {
    name: "TEXT",
    kind: "command",
    category: "Graphics",
    syntax: [
      "TEXT x, y, string$ [, alignment$] [, font] [, scale] [, c] [, bc]",
    ],
    summary: "Draws text on a graphics display.",
    notes: [
      "Alignment is two letters: L, C or R for horizontal, T, M or B for vertical.",
      "Add R, U, D or L to the alignment string to rotate the text.",
    ],
    example: ['TEXT 10, 10, "Hello", "LT", 1, 2, RGB(WHITE)'].join("\n"),
    snippet: 'TEXT ${1:x}, ${2:y}, "${3:text}", "${4|LT,CT,RT,LM,CM,RM,LB,CB,RB|}"',
  },
  {
    name: "FONT",
    kind: "command",
    category: "Graphics",
    syntax: ["FONT [#]font-number, scaling"],
    summary: "Selects the default font and scale for later text output.",
    example: ["FONT 1, 2"].join("\n"),
    snippet: "FONT ${1:1}, ${2:1}",
  },
  {
    name: "DEFINEFONT",
    kind: "command",
    category: "Graphics",
    syntax: ["DEFINEFONT #Nbr", "  hex ...", "END DEFINEFONT"],
    summary: "Embeds a user defined font in the program as hex data.",
    snippet: "DEFINEFONT #${1:8}\n$0\nEND DEFINEFONT",
  },
  {
    name: "COLOUR",
    kind: "command",
    category: "Graphics",
    syntax: ["COLOUR fore [, back]", "COLOR fore [, back]"],
    summary:
      "Sets the default foreground and background colours for text and drawing.",
    example: ["COLOUR RGB(WHITE), RGB(BLACK)"].join("\n"),
    snippet: "COLOUR ${1:RGB(WHITE)}, ${2:RGB(BLACK)}",
  },
  {
    name: "COLOR",
    kind: "command",
    category: "Graphics",
    syntax: ["COLOR fore [, back]"],
    summary: "American spelling of COLOUR. Identical behaviour.",
    snippet: "COLOR ${1:RGB(WHITE)}, ${2:RGB(BLACK)}",
  },
  {
    name: "RGB",
    kind: "function",
    category: "Graphics",
    syntax: ["RGB( red, green, blue )", "RGB( shortcut )"],
    summary:
      "Builds a 24 bit colour value. Named shortcuts save typing the components.",
    notes: [
      "Shortcuts: WHITE, BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, YELLOW, BROWN, GREY, LITEGREY and more.",
    ],
    example: ["c = RGB(255, 128, 0)", "c = RGB(CYAN)"].join("\n"),
    snippet: "RGB(${1|WHITE,BLACK,RED,GREEN,BLUE,CYAN,MAGENTA,YELLOW,GREY|})",
  },
  {
    name: "MAP",
    kind: "command",
    category: "Graphics",
    syntax: [
      "MAP( n ) = rgb%",
      "MAP SET",
      "MAP RESET",
      "MAP MAXIMITE",
      "MAP GREYSCALE",
    ],
    summary:
      "Edits the colour palette in paletted display modes. MAP SET applies the changes.",
    snippet: "MAP(${1:n}) = ${2:RGB(WHITE)}",
  },
  {
    name: "MODE",
    kind: "command",
    category: "Graphics",
    syntax: ["MODE n"],
    summary:
      "Selects the display mode, which sets resolution and colour depth. Available modes depend on the firmware build.",
    snippet: "MODE ${1:1}",
  },
  {
    name: "RESOLUTION",
    kind: "command",
    category: "Graphics",
    syntax: ["RESOLUTION nn [, cpuspeedinKHz]"],
    summary: "Sets the video output resolution on builds that support it.",
    snippet: "RESOLUTION ${1:nn}",
  },
  {
    name: "REFRESH",
    kind: "command",
    category: "Graphics",
    syntax: ["REFRESH"],
    summary:
      "Pushes the framebuffer to the display when OPTION AUTOREFRESH is OFF.",
  },
  {
    name: "FRAMEBUFFER",
    kind: "command",
    category: "Graphics",
    syntax: [
      "FRAMEBUFFER CREATE [2]",
      "FRAMEBUFFER LAYER [colour]",
      "FRAMEBUFFER WRITE where",
      "FRAMEBUFFER COPY from, to [, b]",
      "FRAMEBUFFER MERGE [colour] [, mode] [, updaterate]",
      "FRAMEBUFFER WAIT",
      "FRAMEBUFFER SYNC",
      "FRAMEBUFFER CLOSE [which]",
    ],
    summary:
      "Creates off screen buffers and layers, so you can draw without flicker and then copy or merge to the display.",
    example: [
      "FRAMEBUFFER CREATE",
      "FRAMEBUFFER WRITE F",
      "CLS",
      "CIRCLE 100, 100, 40",
      "FRAMEBUFFER COPY F, N",
    ].join("\n"),
    snippet: "FRAMEBUFFER ${1|CREATE,LAYER,WRITE,COPY,MERGE,WAIT,SYNC,CLOSE|}",
  },
  {
    name: "BLIT",
    kind: "command",
    category: "Graphics",
    syntax: [
      "BLIT x1, y1, x2, y2, w, h",
      "BLIT READ [#]b, x, y, w, h",
      "BLIT WRITE [#]b, x, y [, mode]",
      "BLIT LOAD [#]b, fname$ [, x] [, y] [, w] [, h]",
      "BLIT MEMORY address, x, y [, col]",
      "BLIT FRAMEBUFFER from, to, xin, yin, xout, yout, width, height [, colour]",
      "BLIT COMPRESSED address%, x, y [, col]",
      "BLIT RESIZE src, dst, sx, sy, sw, sh, dx, dy, dw, dh [, transparent]",
      "BLIT MERGE colour, x, y, w, h",
      "BLIT CLOSE [#]b",
    ],
    summary:
      "Copies rectangles of pixels around the screen or between memory buffers.",
    notes: ["Mode bit 1 is mirror horizontally, bit 2 mirror vertically, bit 4 transparent."],
    example: [
      "BLIT READ #1, 0, 0, 32, 32",
      "BLIT WRITE #1, 100, 100",
      "BLIT CLOSE #1",
    ].join("\n"),
    snippet: "BLIT ${1|READ,WRITE,LOAD,MEMORY,FRAMEBUFFER,CLOSE|}",
  },
  {
    name: "SPRITE",
    kind: "command",
    category: "Graphics",
    syntax: [
      "SPRITE LOAD #n, fname$",
      "SPRITE SHOW #n, x, y, layer [, flags]",
      "SPRITE MOVE",
      "SPRITE HIDE #n",
      "SPRITE NEXT #n, x, y",
      "SPRITE CLOSE [#n]",
      "SPRITE SCROLL x, y [, colour]",
    ],
    summary:
      "Hardware assisted sprites with collision detection and layer ordering.",
    snippet: "SPRITE ${1|LOAD,SHOW,MOVE,HIDE,NEXT,SCROLL,CLOSE|}",
  },
  {
    name: "SPRITE(",
    kind: "function",
    category: "Graphics",
    syntax: ["SPRITE( ... )"],
    summary:
      "Reads sprite state: position, collisions, size and the number of active sprites.",
    snippet: "SPRITE(${1:args})",
  },
  {
    name: "TILE",
    kind: "command",
    category: "Graphics",
    syntax: [
      "TILE x, y [, foreground] [, background] [, tiles_wide] [, tiles_high]",
      "TILE HEIGHT n",
    ],
    summary:
      "Sets the colour of character cells in tiled text modes without redrawing them.",
    snippet: "TILE ${1:x}, ${2:y}, ${3:RGB(WHITE)}, ${4:RGB(BLACK)}",
  },
  {
    name: "TILEMAP",
    kind: "command",
    category: "Graphics",
    syntax: ["TILEMAP ..."],
    summary: "Tilemap based background rendering for games.",
  },
  {
    name: "TURTLE",
    kind: "command",
    category: "Graphics",
    syntax: ["TURTLE ..."],
    summary: "Turtle graphics drawing commands.",
  },
  {
    name: "DRAW3D",
    kind: "command",
    category: "Graphics",
    syntax: ["DRAW3D ..."],
    summary: "Wireframe 3D drawing engine commands.",
  },
  {
    name: "MANDELBROT",
    kind: "command",
    category: "Graphics",
    syntax: [
      "MANDELBROT DRAW [maxiter]",
      "MANDELBROT PAN dx, dy",
      "MANDELBROT ZOOM factor",
      "MANDELBROT CENTRE x, y",
      "MANDELBROT RESET",
    ],
    summary: "Built in Mandelbrot set renderer.",
    snippet: "MANDELBROT ${1|DRAW,PAN,ZOOM,CENTRE,RESET|}",
  },
  {
    name: "GUI",
    kind: "command",
    category: "GUI",
    syntax: [
      "GUI BITMAP x, y, bits [, width] [, height] [, scale] [, c] [, bc]",
      "GUI CALIBRATE [a, b, c, d, e]",
      "GUI CURSOR ON|OFF|SHOW|HIDE ...",
      "GUI CLICK ...",
      "GUI TEST LCDPANEL|TOUCH",
      "GUI RESET LCDPANEL",
    ],
    summary:
      "Touch calibration, cursor control and display test patterns.",
    snippet: "GUI ${1|BITMAP,CALIBRATE,CURSOR,CLICK,TEST,RESET|}",
  },
  {
    name: "TOUCH",
    kind: "function",
    category: "Touch",
    syntax: [
      "TOUCH( X ) / TOUCH( Y )",
      "TOUCH( DOWN ) / TOUCH( UP )",
      "TOUCH( X2 ) / TOUCH( Y2 ) / TOUCH( XN n ) / TOUCH( YN n )",
      "TOUCH( TAP ) / TOUCH( DTAP ) / TOUCH( TTAP ) / TOUCH( HOLD )",
      "TOUCH( SWIPE ) / TOUCH( SWL ) / TOUCH( SWR ) / TOUCH( SWU ) / TOUCH( SWD )",
      "TOUCH( PINCH ) / TOUCH( EXPAND ) / TOUCH( CONTRACT )",
      "TOUCH( ROTATE ) / TOUCH( CW ) / TOUCH( CCW )",
    ],
    summary:
      "Reads the touch panel: coordinates, press state and recognised gestures.",
    example: [
      "IF TOUCH(DOWN) THEN PRINT TOUCH(X), TOUCH(Y)",
    ].join("\n"),
    snippet: "TOUCH(${1|X,Y,DOWN,UP,TAP,HOLD,SWIPE|})",
  },
  {
    name: "CLICK",
    kind: "function",
    category: "Touch",
    syntax: [
      "CLICK( DOWN ) / CLICK( UP )",
      "CLICK( X ) / CLICK( Y )",
      "CLICK( REF ) / CLICK( LASTREF )",
      "CLICK( LASTX ) / CLICK( LASTY )",
    ],
    summary:
      "Reads the mouse or touch click state used by the GUI cursor system.",
    snippet: "CLICK(${1|DOWN,UP,X,Y,REF,LASTREF|})",
  },
  {
    name: "GETSCANLINE",
    kind: "function",
    category: "Graphics",
    syntax: ["GETSCANLINE"],
    summary:
      "The scan line the video output is currently drawing. Useful for tear free updates.",
  },
  {
    name: "IMAGE",
    kind: "command",
    category: "Graphics",
    syntax: ["IMAGE ..."],
    summary: "Image manipulation commands such as resize and rotate.",
  },
];
